services:
  mysql:
    image: mysql:8.0
    container_name: student-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: student_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: student-redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: student-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis

  frontend:
    build: ./frontend
    container_name: student-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
